import { MedusaService } from "@medusajs/framework/utils";
import { TurfAttributes } from "./models";

/**
 * Turf Attributes Service
 *
 * Provides methods for managing turf attributes.
 */
export default class TurfAttributesService extends MedusaService({
  TurfAttributes,
}) {
  // CRUD methods are auto-generated by MedusaService:
  // - createTurfAttributes(data)
  // - updateTurfAttributes(id, data)
  // - deleteTurfAttributes(id)
  // - retrieveTurfAttributes(id)
  // - listTurfAttributes(filters, config)
}
